### ISSUE TITLE
table height?

### ISSUE THREAD

**Issue by tbeason** [pdeffebach/FloatingTableView.jl#12]
I'm having trouble changing table height. It seems the width is dynamic as I change the window, but I am always stuck with basically a fixed table height (which is very small relative to my available screen real estate). I see there is a `height` kwarg but I have not successfully used it yet.

**Comment by pdeffebach** [comment]
I just confirmed this on mac. I have no idea how to fix this, though, since this package is just a call to `Blink.window`. I'll see if I can figure something out.

**Comment by jacobadenbaum** [comment]
I just saw this package, and I immediately noticed this issue.  You can fix it by calling `showtable` with the default argument `showtable(df, height = "100vh")`.  Happy to make a PR with this fix if it would be helpful!  In the interim, you can change this behavior automatically since it looks like browse passes through arbitrary keyword arguments.

**Comment by pdeffebach** [comment]
Oh wonderful! 

I will start a PR right away

**Comment by jacobadenbaum** [comment]
sorry!  was 3/4 through the PR when you replied, so I figured I'd just finish it anyway
